### ISSUE TITLE
Can't use slider as attribute

### ISSUE THREAD

**Issue by micrum** [seiyria/angular-bootstrap-slider#101]
Trying to use slider as attribute:
 
    <span slider ng-model="sliders.secondSliderValue" min="0"></span>

The result is code wrapped in `<div>`, not `<span>`:

    <div slider="" ng-model="sliders.secondSliderValue" min="0" class="ng-isolate-scope ng-valid">
        <div class="slider slider-horizontal" id="" style="width: 100%;"> ... </div>
        <input class="slider-input" type="text" style="width: 100%; display: none;" data-value="0" value="0"> 
    </div>

**Comment by seiyria** [comment]
So it's not that you can't use it as an attribute, because it probably works, but rather that it's not wrapped in the right element.

Unfortunately, the `<div>` comes from bootstrap-slider, so this is not going to change. I suspect you would not want a `<div>` in a `<span>` anyway, so it might be best to make it work as-is.
